/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2021-03-23 18:30:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dao.WishlistDao;
import com.bean.Wishlist;
import com.dao.UserDao;
import java.util.List;
import com.dao.ServiceDao;
import com.bean.Service;
import com.bean.User;

public final class mywishlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1616522241926L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.dao.ServiceDao");
    _jspx_imports_classes.add("com.bean.Wishlist");
    _jspx_imports_classes.add("com.bean.User");
    _jspx_imports_classes.add("com.dao.WishlistDao");
    _jspx_imports_classes.add("com.dao.UserDao");
    _jspx_imports_classes.add("com.bean.Service");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <title>Home Creation</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- core CSS -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/prettyPhoto.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/icomoon.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"js/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/ico/favicon.ico\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"images/ico/apple-touch-icon-144-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"images/ico/apple-touch-icon-114-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"images/ico/apple-touch-icon-72-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"images/ico/apple-touch-icon-57-precomposed.png\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<!--/head-->\r\n");
      out.write("\r\n");
      out.write("<body class=\"homepage\">\r\n");
      out.write("\t");

		User u = null;
		if (session != null) {
			if (session.getAttribute("u") != null) {
				u = (User) session.getAttribute("u");
			}
		}
	
      out.write("\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"top-bar\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"top-number\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-phone-square\"></i> +918054203882\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"social\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"social-share\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (u != null) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"ti-power-off\"><a href=\"mycart.jsp\">Cart</a></i>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"ti-power-off\"><a href=\"mywishlist.jsp\">Wishlist</a></i>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"ti-power-off\"></i><a href=\"signout.jsp\">SignOut</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									} else {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"ti-power-off\"></i><a href=\"signin.jsp\">SignIn</a></li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"ti-power-off\"></i><a href=\"signup.jsp\">SignUp</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form role=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"search-form\" autocomplete=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"Search\"> <i class=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/.container-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--/.top-bar-->\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\" role=\"banner\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\".navbar-collapse\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/logo.png\" alt=\"logo\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse navbar-right\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"about-us.jsp\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"services.jsp\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"portfolio.jsp\">Portfolio</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\">Pages <i class=\"fa fa-angle-down\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"blog-item.jsp\">Blog Single</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pricing.jsp\">Pricing</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"404.jsp\">404</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"blog.jsp\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"contact-us.jsp\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/.container-->\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<!--/nav-->\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!--/header-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
 
	
   List<Wishlist>list= WishlistDao.getMyWishlist(u.getId());

      out.write("\r\n");
      out.write("    <section id=\"main-slider\" class=\"no-margin\">\r\n");
      out.write("        <div class=\"carousel slide\">\r\n");
      out.write("            <ol class=\"carousel-indicators\">\r\n");
      out.write("                <li data-target=\"#main-slider\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                <li data-target=\"#main-slider\" data-slide-to=\"1\"></li>\r\n");
      out.write("                <li data-target=\"#main-slider\" data-slide-to=\"2\"></li>\r\n");
      out.write("            </ol>\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"item active\" style=\"background-image: url(images/slider/bg1.jpg)\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-7\">\r\n");
      out.write("                                <div class=\"carousel-content\">\r\n");
      out.write("                                    <h1 class=\"animation animated-item-1\">Help Finding Information Online</h1>\r\n");
      out.write("                                    <div class=\"animation animated-item-2\">\r\n");
      out.write("                                        Every new computer thats brought home from the store has an operating system installed onto it.\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <a class=\"btn-slide animation animated-item-3\" href=\"#\">Learn More</a>\r\n");
      out.write("                                    <a class=\"btn-slide white animation animated-item-3\" href=\"#\">Get Started</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--/.item-->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"item\" style=\"background-image: url(images/slider/bg2.jpg)\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-7\">\r\n");
      out.write("                                <div class=\"carousel-content\">\r\n");
      out.write("                                    <h1 class=\"animation animated-item-1\">Help Finding Information Online</h1>\r\n");
      out.write("                                    <div class=\"animation animated-item-2\">\r\n");
      out.write("                                        Every new computer thats brought home from the store has an operating system installed onto it.\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <a class=\"btn-slide white animation animated-item-3\" href=\"#\">Learn More</a>\r\n");
      out.write("                                    <a class=\"btn-slide animation animated-item-3\" href=\"#\">Get Started</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--/.item-->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--/.carousel-inner-->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--/.carousel-->\r\n");
      out.write("        <a class=\"prev hidden-xs hidden-sm\" href=\"#main-slider\" data-slide=\"prev\">\r\n");
      out.write("            <i class=\"fa fa-chevron-left\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"next hidden-xs hidden-sm\" href=\"#main-slider\" data-slide=\"next\">\r\n");
      out.write("            <i class=\"fa fa-chevron-right\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"services\" class=\"service-item\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"center fadeInDown\">\r\n");
      out.write("                <h2>Our Service</h2>\r\n");
      out.write("                <p class=\"lead\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("             ");

             for(Wishlist w:list) 
             {
            	 Service s=ServiceDao.getServiceById(w.getSid());
             
      out.write("\r\n");
      out.write("                <div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("                    <div class=\"media services-wrap fadeInDown\">\r\n");
      out.write("                        <div class=\"pull-left\">\r\n");
      out.write("                            <img class=\"img-responsive\" src=\"upload/");
      out.print(s.getImage());
      out.write("\" width=\"200px\" height=\"200px\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div> \r\n");
      out.write("                            <h3 class=\"media-heading\">");
      out.print(s.getSrvicename() );
      out.write("</h3>\r\n");
      out.write("                            <p>");
      out.print(s.getPrice() );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                     \r\n");
      out.write("                   <a href=\"remove_from_wishlist.jsp?wid=");
      out.print(w.getId());
      out.write("\"><input type=\"button\"  name=\"action\" value=\"Remove from Wishlist\"></a>\r\n");
      out.write("                    <a href=\"cartlist.jsp?uid=");
      out.print(u.getId());
      out.write("&sid=");
      out.print(s.getId());
      out.write("\"><input type=\"button\"  name=\"action\" value=\"Add to Cartlist\"></a>\r\n");
      out.write("              \r\n");
      out.write("                   </div> \r\n");
      out.write("             \r\n");
      out.write("              ");
} 
      out.write("  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--/.row-->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--/.container-->\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--/#services-->\r\n");
      out.write("    <section id=\"middle\" class=\"skill-area\" style=\"background-image: url(images/skill-bg.png)\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-12 fadeInDown\">\r\n");
      out.write("                    <div class=\"skill\">\r\n");
      out.write("                        <h2>Our Skills</h2>\r\n");
      out.write("                        <p>All users on MySpace will know that there are millions of people out there. Every <br> day besides so many people joining this community.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--/.col-sm-6-->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"progress-wrap\">\r\n");
      out.write("                        <h3>Graphic Design</h3>\r\n");
      out.write("                        <div class=\"progress\">\r\n");
      out.write("                            <div class=\"progress-bar  color1\" role=\"progressbar\" aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 85%\">\r\n");
      out.write("                                <span class=\"bar-width\">85%</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"progress-wrap\">\r\n");
      out.write("                        <h3>HTML</h3>\r\n");
      out.write("                        <div class=\"progress\">\r\n");
      out.write("                            <div class=\"progress-bar color2\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 95%\">\r\n");
      out.write("                                <span class=\"bar-width\">95%</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"progress-wrap\">\r\n");
      out.write("                        <h3>CSS</h3>\r\n");
      out.write("                        <div class=\"progress\">\r\n");
      out.write("                            <div class=\"progress-bar color3\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 80%\">\r\n");
      out.write("                                <span class=\"bar-width\">80%</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"progress-wrap\">\r\n");
      out.write("                        <h3>Wordpress</h3>\r\n");
      out.write("                        <div class=\"progress\">\r\n");
      out.write("                            <div class=\"progress-bar color4\" role=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 90%\">\r\n");
      out.write("                                <span class=\"bar-width\">90%</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--/.row-->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--/.container-->\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--/#middle-->\r\n");
      out.write("\r\n");
      out.write("    <section id=\"content\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xs-12 col-sm-10 col-sm-offset-1 fadeInDown\">\r\n");
      out.write("                    <div class=\"tab-wrap\">\r\n");
      out.write("                        <div class=\"media\">\r\n");
      out.write("                            <div class=\"parrent pull-left\">\r\n");
      out.write("                                <ul class=\"nav nav-tabs nav-stacked\">\r\n");
      out.write("                                    <li class=\"\"><a href=\"#tab1\" data-toggle=\"tab\" class=\"analistic-01\">Responsive Web Design</a></li>\r\n");
      out.write("                                    <li class=\"active\"><a href=\"#tab2\" data-toggle=\"tab\" class=\"analistic-02\">Premium Plugin Included</a></li>\r\n");
      out.write("                                    <li class=\"\"><a href=\"#tab3\" data-toggle=\"tab\" class=\"tehnical\">Predefine Layout</a></li>\r\n");
      out.write("                                    <li class=\"\"><a href=\"#tab4\" data-toggle=\"tab\" class=\"tehnical\">Our Philosopy</a></li>\r\n");
      out.write("                                    <li class=\"\"><a href=\"#tab5\" data-toggle=\"tab\" class=\"tehnical\">What We Do?</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"parrent media-body\">\r\n");
      out.write("                                <div class=\"tab-content\">\r\n");
      out.write("                                    <div class=\"tab-pane fade\" id=\"tab1\">\r\n");
      out.write("                                        <div class=\"media\">\r\n");
      out.write("                                            <div class=\"pull-left\">\r\n");
      out.write("                                                <img class=\"img-responsive\" src=\"images/tab2.png\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h2>Adipisicing elit</h2>\r\n");
      out.write("                                                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use.</p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"tab-pane fade active in text-right\" id=\"tab2\">\r\n");
      out.write("                                        <div class=\"video-box\">\r\n");
      out.write("                                            <img src=\"images/tab-video-bg.png\" alt=\"video\">\r\n");
      out.write("                                            <a class=\"video-icon\" href=\"http://www.youtube.com/watch?v=cH6kxtzovew\" rel=\"prettyPhoto\"><i class=\"fa fa-play\"></i></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"tab-pane fade\" id=\"tab3\">\r\n");
      out.write("                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"tab-pane fade\" id=\"tab4\">\r\n");
      out.write("                                        <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"tab-pane fade\" id=\"tab5\">\r\n");
      out.write("                                        <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures,</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!--/.tab-content-->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!--/.media-body-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--/.media-->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!--/.tab-wrap-->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--/.col-sm-6-->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--/.row-->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--/.container-->\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--/#content-->\r\n");
      out.write("\r\n");
      out.write("    <section id=\"testimonial\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"center fadeInDown\">\r\n");
      out.write("                <h2>Testimonials</h2>\r\n");
      out.write("                <p class=\"lead\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"testimonial-slider owl-carousel\">\r\n");
      out.write("                <div class=\"single-slide\">\r\n");
      out.write("                    <div class=\"slide-img\">\r\n");
      out.write("                        <img src=\"images/client1.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"content\">\r\n");
      out.write("                        <img src=\"images/review.png\" alt=\"\">\r\n");
      out.write("                        <p>If you are looking at blank cassettes on the web, you may be very confused at the difference in price.</p>\r\n");
      out.write("                        <h4>- Charlotte Daniels</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"single-slide\">\r\n");
      out.write("                    <div class=\"slide-img\">\r\n");
      out.write("                        <img src=\"images/client2.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"content\">\r\n");
      out.write("                        <img src=\"images/review.png\" alt=\"\">\r\n");
      out.write("                        <p>If you are looking at blank cassettes on the web, you may be very confused at the difference in price.</p>\r\n");
      out.write("                        <h4>- Charlotte Daniels</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"single-slide\">\r\n");
      out.write("                    <div class=\"slide-img\">\r\n");
      out.write("                        <img src=\"images/client3.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"content\">\r\n");
      out.write("                        <img src=\"images/review.png\" alt=\"\">\r\n");
      out.write("                        <p>If you are looking at blank cassettes on the web, you may be very confused at the difference in price.</p>\r\n");
      out.write("                        <h4>- Charlotte Daniels</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"single-slide\">\r\n");
      out.write("                    <div class=\"slide-img\">\r\n");
      out.write("                        <img src=\"images/client2.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"content\">\r\n");
      out.write("                        <img src=\"images/review.png\" alt=\"\">\r\n");
      out.write("                        <p>If you are looking at blank cassettes on the web, you may be very confused at the difference in price.</p>\r\n");
      out.write("                        <h4>- Charlotte Daniels</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"single-slide\">\r\n");
      out.write("                    <div class=\"slide-img\">\r\n");
      out.write("                        <img src=\"images/client1.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"content\">\r\n");
      out.write("                        <img src=\"images/review.png\" alt=\"\">\r\n");
      out.write("                        <p>If you are looking at blank cassettes on the web, you may be very confused at the difference in price.</p>\r\n");
      out.write("                        <h4>- Charlotte Daniels</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"single-slide\">\r\n");
      out.write("                    <div class=\"slide-img\">\r\n");
      out.write("                        <img src=\"images/client3.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"content\">\r\n");
      out.write("                        <img src=\"images/review.png\" alt=\"\">\r\n");
      out.write("                        <p>If you are looking at blank cassettes on the web, you may be very confused at the difference in price.</p>\r\n");
      out.write("                        <h4>- Charlotte Daniels</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"partner\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"center fadeInDown\">\r\n");
      out.write("                <h2>Our Partners</h2>\r\n");
      out.write("                <p class=\"lead\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"partners\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\"><img class=\"img-responsive fadeInDown\" data-wow-duration=\"1000ms\" data-wow-delay=\"300ms\" src=\"images/partners/brand-1.png\"></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\"><img class=\"img-responsive fadeInDown\" data-wow-duration=\"1000ms\" data-wow-delay=\"600ms\" src=\"images/partners/brand-2.png\"></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\"><img class=\"img-responsive fadeInDown\" data-wow-duration=\"1000ms\" data-wow-delay=\"900ms\" src=\"images/partners/brand-3.png\"></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\"><img class=\"img-responsive fadeInDown\" data-wow-duration=\"1000ms\" data-wow-delay=\"1200ms\" src=\"images/partners/brand-4.png\"></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\"><img class=\"img-responsive fadeInDown\" data-wow-duration=\"1000ms\" data-wow-delay=\"1500ms\" src=\"images/partners/brand-5.png\"></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--/.container-->\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--/#partner-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section id=\"bottom\">\r\n");
      out.write("        <div class=\"container fadeInDown\" data-wow-duration=\"1000ms\" data-wow-delay=\"600ms\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-2\">\r\n");
      out.write("                    <a href=\"#\" class=\"footer-logo\">\r\n");
      out.write("                        <img src=\"images/logo-black.png\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-10\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                            <div class=\"widget\">\r\n");
      out.write("                                <h3>Company</h3>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\">About us</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">We are hiring</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Meet the team</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Copyright</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Terms of use</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Privacy policy</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--/.col-md-3-->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                            <div class=\"widget\">\r\n");
      out.write("                                <h3>Support</h3>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\">Faq</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Forum</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Documentation</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Refund policy</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Ticket system</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Billing system</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--/.col-md-3-->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                            <div class=\"widget\">\r\n");
      out.write("                                <h3>Developers</h3>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\">Web Development</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">SEO Marketing</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Theme</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Development</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Email Marketing</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Plugin Development</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Article Writing</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--/.col-md-3-->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                            <div class=\"widget\">\r\n");
      out.write("                                <h3>Our Partners</h3>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"#\">Adipisicing Elit</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Eiusmod</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Tempor</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Veniam</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Exercitation</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Ullamco</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Laboris</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--/.col-md-3-->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--/#bottom-->\r\n");
      out.write("\r\n");
      out.write("    <footer id=\"footer\" class=\"midnight-blue\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    &copy; 2013 <a target=\"_blank\" href=\"http://shapebootstrap.net/\" title=\"Free Twitter Bootstrap WordPress Themes and HTML templates\">ShapeBootstrap</a>. All Rights Reserved.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <ul class=\"pull-right\">\r\n");
      out.write("                        <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Faq</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!--/#footer-->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/jquery.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.isotope.min.js\"></script>\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
